server {
    listen 80;
    server_name localhost;

    # Lo que empiece por /api se va al motor de IA
    location /api/ {
        proxy_pass http://ai-engine:8000/;
        proxy_set_header Host $host;
    }

    # El resto se va a la web de gestión
    location / {
        proxy_pass http://backend-django:8080;
        proxy_set_header Host $host;
    }
}