# Generated by Django 6.0.1 on 2026-05-04 16:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntos_clave', models.JSONField()),
                ('banderas_rojas', models.JSONField()),
                ('riesgo_total', models.TextField()),
                ('tipo', models.TextField()),
                ('archivo', models.FileField(upload_to='contratos/%Y/%m/%d/')),
                ('nombre_archivo', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.TextField()),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditorias_propias', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
